# Generated by Django 2.1.4 on 2018-12-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181230_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.IntegerField(default=0)),
                ('rating_likes', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('rating_dislikes', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
            ],
        ),
    ]
